### ISSUE TITLE
 RSAC-FHTET 5-yr section only showing 2011

### ISSUE THREAD

**Issue by geoderek** [nemac/fswms#47]
After we add "Archived Forest Disturbance Detection" theme,

Then scroll down to the RSAC-FHTET 3-yr and 5-yr section

we see that only the maps from 2011 are present

yet we checked the sftp directories, and *all* years are present for these two sets of maps

What happened?   Why did these other years disappear from the archive?

We need to have all of the other years added back in to the Archived theme for both of these RSAC-FHTET products, please.

**Comment by mwhutchi** [comment]
RSAC discontinued the 5-year product. This was removed from the scripts and the EFETAC-NASA was added.
