### ISSUE TITLE
New Events Theme and Accordion Group added to ews_config.tpl.xml

### ISSUE THREAD

**Issue by mwhutchi** [nemac/fswms#73]

**Comment by mwhutchi** [comment]
New view added at the end of the <mapviews> section:
<view name="MODIS_Disturbance_Events" label="Disturbances Assessed">
      <viewGroup name="US_Jurisdictions" />
      <viewGroup name="MODIS_Disturbance_Events" />	
      <viewGroup name="US_Fire" />
      <viewGroup name="US_FHM_ADS" />
      <viewGroup name="MODIS_Change_Detection_Products" />
      <viewGroup name="Archived_TACS" />
      <viewGroup name="MODISCloud" />
      <viewGroup name="Archived_RSAC" />
      <viewGroup name="Drought_Monitor" />
      <viewGroup name="vegdri_new" />
      <viewGroup name="US_Climate" />
      <viewGroup name="US_Physiographic" />	
</view>

And here is the new wms group to be added:

<wmsGroup gid="G17" name="MODIS_Disturbance_Events" label="Disturbances Assessed"> 
    <wmsSubgroup label="Disturbances Assessed">
        <wmsLayer
          selected="false"
          lid="DEAAA"
          visible="true"
          url="%(SERVER_URL)s/wlayers?TRANSPARENT=true"
          srs="EPSG:3785"
          layers="events-current"
          name="Current Year Events"
          styles="default" 
          identify="true"
          legend="%(SERVER_URL)s/wlayers?SERVICE=WMS&amp;REQUEST=GetLegendGraphic&amp;layer=events-current&amp;VERSION=1.1.1&amp;FORMAT=image/png"/>
	<wmsLayer
          selected="false"
          lid="DEAAB"
          visible="true"
          url="%(SERVER_URL)s/wlayers?TRANSPARENT=true"
          srs="EPSG:3785"
          layers="events-historical"
          name="Historical Events"
          styles="default" 
          identify="true"
          legend="%(SERVER_URL)s/wlayers?SERVICE=WMS&amp;REQUEST=GetLegendGraphic&amp;layer=events-historical&amp;VERSION=1.1.1&amp;FORMAT=image/png"/>
      </wmsSubgroup>
  </wmsGroup>

**Comment by geoderek** [comment]
done and deployed
